apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-security
  labels:
    app: service-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-security
  template:
    metadata:
      labels:
        app: service-security
    spec:
      containers:
      - name: app-security
        image: juliocm18/app-security:7
        ports:
        - containerPort: 5001
        env:
        - name: NACOS_SERVERADDR
          value: "143.244.222.245:8848"
        - name: NACOS_NAMESPACE
          value: "config-service-test"
        - name: NACOS_IDENTITYKEY
          value: "nacos"
        - name: NACOS_IDENTITYVALUE
          value: "nacos"
        - name: NACOS_ENV
          value: "config-service-test"